package com.aliothmoon.preferences

/**
 * 标记一个 DataStore 偏好字段：@PrefSchema 类内被标注的属性由 KSP 生成 schema 访问器
 *
 * Marks a DataStore preference field; inside a [PrefSchema] class, annotated properties get
 * schema accessors generated by KSP.
 */
@Target(AnnotationTarget.PROPERTY)
@Retention(AnnotationRetention.SOURCE)
annotation class PrefKey(
    /**
     * 存储用的原始键名；缺省时按 camelToSnakeCase 转换（useGithubMirror → use_github_mirror）。
     * DataStore 迁移必须使用这份 snake_case 原始键
     * / Raw key stored in preferences; defaults to camelToSnakeCase of the property name
     * (useGithubMirror → use_github_mirror). Migrations must use these snake_case raw keys.
     */
    val name: String = "",
    /**
     * 默认值的字面形式，按字段类型自动转换
     * / Literal default value, converted automatically to the field's type.
     */
    val default: String = ""
)
