package com.azurpilot.ghio.di

import androidx.datastore.core.DataStore
import androidx.datastore.core.DataStoreFactory
import androidx.datastore.core.handlers.ReplaceFileCorruptionHandler
import androidx.datastore.dataStoreFile
import com.azurpilot.ghio.AppDispatchers
import com.azurpilot.ghio.auth.AppLockManager
import com.azurpilot.ghio.config.DataStoreUserConfigurationStore
import com.azurpilot.ghio.config.UserConfigurationSerializer
import com.azurpilot.ghio.config.UserConfigurationStore
import com.azurpilot.ghio.constant.DataStoreFile
import com.azurpilot.ghio.domain.UserConfiguration
import com.azurpilot.ghio.domain.license.AssetLicenseRepository
import com.azurpilot.ghio.domain.license.LicenseRepository
import com.azurpilot.ghio.i18n.LocalizedTextRenderer
import com.azurpilot.ghio.keepalive.KeepAliveManager
import com.azurpilot.ghio.settings.AppSettingsGateway
import com.azurpilot.ghio.settings.AppSettingsManager
import com.azurpilot.ghio.report.DeviceReportClient
import com.azurpilot.ghio.ui.shortcut.ShortcutRequests
import com.azurpilot.ghio.update.AppUpdateManager
import kotlinx.coroutines.CoroutineExceptionHandler
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.SupervisorJob
import org.koin.android.ext.koin.androidContext
import org.koin.core.qualifier.named
import org.koin.dsl.module
import timber.log.Timber

/**
 * 进程级 scope 限定符，避免与其它 CoroutineScope 绑定冲突
 *
 * Process-level scope qualifier, avoiding clashes with other CoroutineScope
 * bindings.
 */
object AppCoroutineScope

/**
 * 核心绑定：进程级协程 scope、[UserConfiguration] 的 JSON DataStore、
 * app 设置、i18n 渲染、更新检查、保活与应用锁
 *
 * 两套持久化在此分家：本模块的 DataStore<UserConfiguration> 走 JSON 序列化器
 * （损坏整份换默认值）；app 设置的 Preferences DataStore 由 [AppSettingsManager]
 * 自建，键名经 `@PrefSchema` 按 camelToSnakeCase 生成，与这边互不相干。
 *
 * Core bindings: the process-level coroutine scope, the JSON DataStore for
 * [UserConfiguration], app settings, i18n rendering, update checking,
 * keep-alive, and the app lock.
 *
 * The two persistence stacks are kept apart: this module's
 * DataStore<UserConfiguration> uses a JSON serializer (corruption swaps in
 * defaults wholesale), while the settings Preferences DataStore is built
 * inside [AppSettingsManager] with keys generated by @PrefSchema via
 * camelToSnakeCase, unrelated to this module's store.
 */
val coreModule = module {
    // SupervisorJob + 兜底异常处理器：scope 内任一协程的未捕获异常只记日志，
    // 不波及其它协程，也不掀翻 scope 本身
    single(named<AppCoroutineScope>()) {
        val handler = CoroutineExceptionHandler { _, throwable ->
            Timber.e(throwable, "AppCoroutineScope uncaught")
        }
        CoroutineScope(SupervisorJob() + AppDispatchers.Default + handler)
    }

    single<DataStore<UserConfiguration>> {
        DataStoreFactory.create(
            serializer = UserConfigurationSerializer,
            corruptionHandler = ReplaceFileCorruptionHandler { UserConfiguration() },
            produceFile = {
                androidContext().dataStoreFile(DataStoreFile.USER_CONFIGRATION)
            },
        )
    }
    single<UserConfigurationStore> { DataStoreUserConfigurationStore(get()) }

    single { AppSettingsManager(androidContext()) }
    single { DeviceReportClient(androidContext()) }
    single<AppSettingsGateway> { get<AppSettingsManager>() }

    single { LocalizedTextRenderer(androidContext()) }
    single { AppUpdateManager(androidContext(), get(named<AppCoroutineScope>()), get<AppSettingsManager>()) }
    single { KeepAliveManager(androidContext(), get(), get(named<AppCoroutineScope>())) }
    single { AppLockManager(get()) }
    single<LicenseRepository> { AssetLicenseRepository(androidContext()) }
    single { ShortcutRequests() }
}
