name: Sync to CNB

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync:
    if: github.repository == 'wess09/AzurPilot-for-Android'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to CNB Repository
        uses: docker://tencentcom/git-sync
        env:
          PLUGIN_TARGET_URL: 'https://cnb.cool/azurpilot/AzurPilot-for-Android.git'
          PLUGIN_AUTH_TYPE: 'https'
          PLUGIN_USERNAME: 'cnb'
          PLUGIN_PASSWORD: ${{ secrets.CNB_TOKEN }}
          PLUGIN_FORCE: 'true'
          PLUGIN_PUSH_TAGS: 'true'
